app:
    resource: "@AppBundle/Controller/"
    type:     annotation
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: transaction
        permanent: true
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"